### ISSUE TITLE
convert command fails when code ends with comment

### ISSUE THREAD

**Issue by eliangcs** [zapier/zapier-platform#142]
### Bug Description

In visual builder, if the custom code ends with a single-line comment `// ...`, `zapier convert` will fail with this traceback:

```
  zapier:convert     at t (/.../zapier-platform-cli/node_modules/prettier/parser-babylon.js:1:264)
  zapier:convert     at Object.parse (/.../zapier-platform-cli/node_modules/prettier/parser-babylon.js:1:214621)
  zapier:convert     at Object.parse$2 [as parse] (/.../zapier-platform-cli/node_modules/prettier/index.js:10629:19)
  zapier:convert     at coreFormat (/.../zapier-platform-cli/node_modules/prettier/index.js:13888:23)
  zapier:convert     at format (/.../zapier-platform-cli/node_modules/prettier/index.js:14146:73)
  zapier:convert     at formatWithCursor (/.../zapier-platform-cli/node_modules/prettier/index.js:14162:12)
  zapier:convert     at /.../zapier-platform-cli/node_modules/prettier/index.js:42756:15
  zapier:convert     at Object.format (/.../zapier-platform-cli/node_modules/prettier/index.js:42775:12)
  zapier:convert     at prettifyJs (/.../zapier-platform-cli/packages/cli/src/utils/convert.js:44:12)
  zapier:convert     at renderStep (/.../zapier-platform-cli/packages/cli/src/utils/convert.js:196:10) +2s
 ›   Error: Unexpected token
```

### Reproduction Steps

1. Create an integration in visual builder
2. Create a trigger or an action
3. Switch to code mode for that trigger/action
4. Edit the code so that it ends with a single-line comment, such as:

```
return {
  'message': 'ok'
};
// this line would break `zapier convert`
```

5. Run `zapier convert APP_ID ./myapp --version 1.0.0 --debug`

### Version Info

```
$ zapier -v
zapier-platform-cli/9.0.0 darwin-x64 node-v10.16.3
```

**Comment by xavdid** [comment]
definitely worth root-causing, but given that it's a pretty specific (and avoidable) cause, i'm not too worried.

**Comment by zapzap** [comment]
This issue has been copied into our private issue tracker  (as [PDE-1290](https://zapierorg.atlassian.net/browse/PDE-1290)). Thanks for the report! We'll update this as we learn more.
